eplicaCount: 3
namespace: r-clone

image:
  repository: confluentinc/cp-kafka
  tag: 7.7.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

persistence:
  enabled: true
  storageClass: "local-path"
  accessMode: ReadWriteOnce
  size: 1Gi

config:
  listeners: 'PLAINTEXT://:9092,CONTROLLER://:9093'
  advertisedListeners: PLAINTEXT://kafka-t:9092
  interBrokerListenerName: PLAINTEXT
  controllerListenerNames: CONTROLLER
  processRoles: broker,controller
  clusterId: "LlA3VAdlSAWKqQZ3Gj0Kdw"
  logRetentionHours: "168"
  logRetentionBytes: "1073741824"
  numPartitions: "1"
  defaultReplicationFactor: "1"
  offsetsTopicReplicationFactor: "1"
  autoCreateTopicsEnable: "true"
  transactionStateLogMinIsr: "1"
  transactionStateLogReplicationFactor: "1"
  groupInitialRebalanceDelay: "0"